name: WFTDA Champs
favicon: null
layout_spectrum: 0.80179
typography_spectrum: 0.64035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-976487-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.25
  lightness: 0.7443970828317106
  saturation: 0.3078274177387357
  rhythmicContrast: 0.764986959984526
purpose: []
